name: Build latest
on: [push]

concurrency:
  group: ${{ github.ref }}-latest
  cancel-in-progress: true

jobs:
  build-mono:
    if: github.ref_name == github.event.repository.default_branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Compile Harmony using mono
        shell: bash
        id: compile
        run: |
          msbuild Flames.sln /p:Configuration=Release
          rm bin/Release/Harmony_.exe bin/Release/Harmony_.pdb
          msbuild Flames/Flames.csproj /p:Configuration=Release /p:DefineConstants="CORE"

      - uses: ./.github/actions/notify_failure
        if: ${{ always() && steps.compile.outcome == 'failure' }}
        with:
          NOTIFY_MESSAGE: 'Failed to compile Harmony .NET build! <@999409543001931788>'
          WEBHOOK_URL: '${{ secrets.WEBHOOK_URL }}'
          
      - uses: ./.github/actions/notify_success
        if: ${{ always() && steps.compile.outcome == 'success' }}
        with:
          SOURCE_FILE: 'bin/Release'
          DEST_NAME: 'Harmony'
          NOTIFY_MESSAGE: 'Successfully compiled Harmony .NET build.'
          WEBHOOK_URL: '${{ secrets.WEBHOOK_URL }}'
          
